# Generated by Django 5.2.3 on 2025-10-29 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(verbose_name='')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Name in Russian')),
                ('name_ua', models.CharField(max_length=100, verbose_name='Name in Ukrainian')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name in English')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(verbose_name='Title')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
